export const JOB_ROLES = [
  "Software Engineer",
  "Associate Software Engineer",
  "Junior Software Engineer",
  "Senior Software Engineer",
  "Staff Software Engineer",
  "Principal Software Engineer",
  "Software Architect",
  "Solutions Engineer",
  "Application Engineer",
  "Systems Engineer",
  "Platform Engineer",
  "Infrastructure Engineer",
  "Tools Engineer",
  "Automation Engineer",

  "Frontend Developer",
  "Junior Frontend Developer",
  "Senior Frontend Developer",
  "UI Engineer",
  "Web Developer",
  "React Developer",
  "Next.js Developer",
  "Angular Developer",
  "Vue Developer",
  "Svelte Developer",
  "Node.js Developer",
  "JavaScript Developer",
  "TypeScript Developer",
  "HTML/CSS Developer",

  "Backend Developer",
  "Junior Backend Developer",
  "Senior Backend Developer",
  "API Developer",
  "REST API Developer",
  "GraphQL Developer",
  "Full Stack Developer",
  "MEAN Stack Developer",
  "MERN Stack Developer",
  "Python Developer",
  "Django Developer",
  "Flask Developer",
  "FastAPI Developer",
  "Java Developer",
  "Spring Boot Developer",
  "Kotlin Developer",
  "C++ Developer",
  "C# Developer",
  ".NET Developer",
  "ASP.NET Developer",
  "Go Developer",
  "Ruby Developer",
  "Ruby on Rails Developer",
  "PHP Developer",
  "Laravel Developer",
  "Perl Developer",
  "Scala Developer",
  "Rust Developer",
  "Elixir Developer",
  "Erlang Developer",
  "Objective-C Developer",
  "Swift Developer",
  "ColdFusion Developer",

  "Mobile Developer",
  "Android Developer",
  "iOS Developer",
  "Flutter Developer",
  "React Native Developer",
  "Xamarin Developer",
  "Mobile App Developer",
  "Mobile Software Engineer",
  "Cross-Platform Developer",

  "Data Scientist",
  "Junior Data Scientist",
  "Senior Data Scientist",
  "Lead Data Scientist",
  "Applied Scientist",
  "Research Scientist",
  "Data Analyst",
  "Business Intelligence Analyst",
  "BI Developer",
  "BI Analyst",
  "Data Engineer",
  "Analytics Engineer",
  "Machine Learning Engineer",
  "Senior Machine Learning Engineer",
  "AI Engineer",
  "MLOps Engineer",
  "Deep Learning Engineer",
  "Computer Vision Engineer",
  "NLP Engineer",
  "Generative AI Engineer",
  "Prompt Engineer",
  "Data Architect",
  "Data Platform Engineer",
  "Quantitative Analyst",
  "Decision Scientist",
  "Statistician",

  "DevOps Engineer",
  "Senior DevOps Engineer",
  "Site Reliability Engineer",
  "SRE",
  "Cloud Engineer",
  "Cloud Architect",
  "AWS Engineer",
  "Azure Engineer",
  "GCP Engineer",
  "Platform Reliability Engineer",
  "Build and Release Engineer",
  "Release Engineer",
  "Infrastructure Automation Engineer",
  "CI/CD Engineer",
  "Linux Administrator",

  "Security Engineer",
  "Cybersecurity Analyst",
  "Cyber Security Engineer",
  "Information Security Analyst",
  "Information Security Engineer",
  "Security Analyst",
  "SOC Analyst",
  "Penetration Tester",
  "Ethical Hacker",
  "Red Team Engineer",
  "Blue Team Analyst",
  "Threat Hunter",
  "Incident Responder",
  "Security Architect",
  "Application Security Engineer",
  "Cloud Security Engineer",
  "Network Security Engineer",
  "GRC Analyst",
  "IAM Engineer",
  "Security Operations Engineer",

  "Network Engineer",
  "Network Administrator",
  "Systems Administrator",
  "System Administrator",
  "Windows Administrator",
  "Linux Administrator",
  "Desktop Support Engineer",
  "IT Support Specialist",
  "Technical Support Engineer",
  "Help Desk Analyst",
  "Service Desk Engineer",
  "Database Administrator",
  "Database Engineer",
  "SQL Developer",
  "Oracle DBA",
  "MySQL DBA",
  "PostgreSQL DBA",
  "MongoDB Administrator",

  "QA Engineer",
  "Quality Assurance Engineer",
  "Test Engineer",
  "Manual Tester",
  "Automation Tester",
  "Test Automation Engineer",
  "SDET",
  "Software Development Engineer in Test",
  "Performance Test Engineer",
  "Load Test Engineer",
  "QA Analyst",
  "UAT Tester",

  "Scrum Master",
  "Agile Coach",
  "Release Train Engineer",
  "Project Manager",
  "Technical Project Manager",
  "Program Manager",
  "Product Manager",
  "Associate Product Manager",
  "Senior Product Manager",
  "Technical Product Manager",
  "Product Owner",
  "Group Product Manager",
  "Head of Product",
  "Engineering Manager",
  "Senior Engineering Manager",
  "Director of Engineering",
  "VP of Engineering",
  "CTO",

  "UX Designer",
  "UI Designer",
  "UX/UI Designer",
  "Product Designer",
  "Interaction Designer",
  "Visual Designer",
  "Graphic Designer",
  "Motion Designer",
  "Web Designer",
  "Brand Designer",
  "Design System Designer",
  "UX Researcher",
  "User Researcher",
  "Design Researcher",
  "Service Designer",
  "Content Designer",
  "Creative Designer",

  "Content Strategist",
  "Content Writer",
  "Copywriter",
  "Technical Writer",
  "Documentation Engineer",
  "Documentation Specialist",
  "Editor",
  "SEO Specialist",
  "SEO Manager",
  "Search Marketing Specialist",
  "Content Marketer",
  "Growth Marketer",
  "Growth Hacker",
  "Performance Marketer",
  "Digital Marketing Manager",
  "Marketing Manager",
  "Social Media Manager",
  "Community Manager",
  "Brand Manager",
  "Email Marketing Specialist",
  "Lifecycle Marketing Manager",
  "Product Marketing Manager",
  "Demand Generation Manager",
  "Field Marketing Manager",
  "Marketing Analyst",

  "Sales Manager",
  "Sales Executive",
  "Account Executive",
  "Account Manager",
  "Business Development Representative",
  "Sales Development Representative",
  "Business Development Manager",
  "Inside Sales Representative",
  "Outside Sales Representative",
  "Sales Engineer",
  "Solutions Architect",
  "Customer Success Manager",
  "Customer Support Specialist",
  "Technical Account Manager",
  "Pre-Sales Consultant",
  "Revenue Operations Analyst",
  "Revenue Operations Manager",

  "Financial Analyst",
  "Senior Financial Analyst",
  "FP&A Analyst",
  "Accountant",
  "Senior Accountant",
  "Bookkeeper",
  "Auditor",
  "Tax Accountant",
  "Controller",
  "Finance Manager",
  "Treasury Analyst",
  "Risk Analyst",
  "Investment Analyst",
  "Portfolio Analyst",
  "Chief Financial Officer",
  "CFO",

  "HR Manager",
  "Human Resources Generalist",
  "Recruiter",
  "Technical Recruiter",
  "Talent Acquisition Specialist",
  "Talent Sourcer",
  "HR Business Partner",
  "People Operations Specialist",
  "Compensation Analyst",
  "Payroll Specialist",
  "L&D Specialist",
  "Employee Relations Specialist",
  "Chief People Officer",

  "Operations Manager",
  "Operations Analyst",
  "Business Operations Manager",
  "Strategy Analyst",
  "Business Analyst",
  "Senior Business Analyst",
  "Systems Analyst",
  "Process Analyst",
  "Workflow Analyst",
  "Program Analyst",
  "Administrative Assistant",
  "Executive Assistant",
  "Office Manager",
  "Supply Chain Analyst",
  "Logistics Coordinator",
  "Procurement Specialist",
  "Vendor Manager",

  "Chief Executive Officer",
  "CEO",
  "Chief Operating Officer",
  "COO",
  "Chief Marketing Officer",
  "CMO",
  "Chief Technology Officer",
  "Chief Product Officer",
  "Chief Information Officer",
  "Chief Information Security Officer",
  "CISO",
  "VP of Product",
  "VP of Sales",
  "VP of Marketing",
  "VP of Operations",
  "VP of Finance",
  "VP of People",
  "Head of Engineering",
  "Head of Design",
  "Head of Marketing",
  "Head of Sales",
  "Head of Operations",

  "Research Engineer",
  "Research Associate",
  "Laboratory Technician",
  "Biomedical Engineer",
  "Bioinformatics Engineer",
  "Computational Biologist",
  "Embedded Software Engineer",
  "Firmware Engineer",
  "Hardware Engineer",
  "Electronics Engineer",
  "Robotics Engineer",
  "Mechatronics Engineer",
  "Automation Specialist",
  "Game Developer",
  "Unity Developer",
  "Unreal Engine Developer",
  "AR/VR Developer",
  "Blockchain Developer",
  "Smart Contract Developer",
  "Solidity Developer",
  "Web3 Developer",
  "ERP Consultant",
  "SAP Consultant",
  "Salesforce Developer",
  "Salesforce Administrator",
  "CRM Administrator",
  "Oracle Developer",
  "Data Privacy Specialist",
  "Compliance Analyst"
];